version: '2'

services:
  portforward:
    build: ./
    image: rhemsjapan/port-forward:latest
    container_name: port-forward-sample
    environment:
      - FORWARD_RDS=3306:sample-rds.xxx.ap-northeast-1.rds.amazonaws.com:3306
      - FORWARD_ELASTICACHE=6379:sample-redis.xxx.apne1.cache.amazonaws.com:6379